### ISSUE TITLE
Difference with std/ws and native WebSocket?

### ISSUE THREAD

**Issue by fonsp** [ryo-ma/deno-websocket#22]
Hey! I was looking for websocket capabilities in deno using google ("deno websocket"), and this was the first result. Later, I found that the [native web API `WebSocket`](https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API) is already supported in deno for ws clients, and there is a [`ws` standard library](https://github.com/denoland/deno_std/tree/main/ws) for hosting a ws server.

Perhaps on the README you could clarify the relation between this package and those two alternatives? Which would you recommend for newcomers?

Thanks! -fons

**Comment by ryo-ma** [comment]
This package is wrapping the native web API Websocket Client and the ws standard library.
You can execute the callback of WebSocket as an EventEmitter.
Good Idea. I will write the description on the README.

**Comment by fonsp** [comment]
I see! So this package would be best for people coming from NodeJS, while people coming from browser JS should use the native WebSocket capabilities?

**Comment by ryo-ma** [comment]
No problem in choosing freely. I will respect the user's choices.
