### ISSUE TITLE
Works Great, more control on Output

### ISSUE THREAD

**Issue by khrome83** [ryo-ma/deno-websocket#4]
This works really great. I am using it as a backchannel for a development server to build hot reloading. 

Would you be open to making a small change, and removing the `console.log("socket connected");

It's minor, but it messes with the log. I would love to have a way to show active or total connections, but I would rather this be an event that is emitted, or status I can fetch and control the output myself.

Thoughts?

**Comment by ryo-ma** [comment]
Thanks!
I think you're right.
I have supported that.

**Comment by khrome83** [comment]
awesome!
