### ISSUE TITLE
Question: Do you plan to publish your module also on https://nest.land/ ?

### ISSUE THREAD

**Issue by michael-spengler** [ryo-ma/deno-websocket#9]
If not - would you mind if I published it there?

https://nest.land/

**Comment by ryo-ma** [comment]
Yeah, If you work on it, I'm glad you.

**Comment by ryo-ma** [comment]
I have done it myself.
https://nest.land/package/deno-websocket

**Comment by michael-spengler** [comment]
perfect - thank you
